# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: AI ML DL U+1F422 KEEP CALM AND CODE ON
email: aimldl@naver.com
description: >- # this means to ignore newlines until "baseurl:"
  Adorable Immature Midget Lagomorph's Dream Land
    where T Kim writes tech blog posts in the field of
  Artificial Intelligence, Machine Learning, Deep Learning.
  Copyright© 2020 All Rights Reserved
baseurl: "" # the subpath of your site, e.g. /blog
url: https://aimldl.github.io # the base hostname & protocol for your site, e.g. http://example.com
github_username:  aimldl
linkedin_username:  mrtonnet
facebook_username:  taehyungtkim
instagram_username: mrtonsurf
dockerhub_username: aimldl

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# multilang
# https://dev-yakuza.posstree.com/en/jekyll/configuration/
languages: ['en', 'ko']
default_lang: 'en'
exclude_from_localization: ['javascript', 'images', 'css']
parallel_localization: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
